make artifacts contain magic.h and libmagic.lib
julian-r/file-windows pull request #13
Opened 2021-09-07 10:17 UTC by Cirn09

I want to write a windows program that depends on libmagic(`magic.h` and `libmagic.lib`), so I added `install` to CMakeLists.txt.

2021-09-10 12:05 UTC, Cirn09 commented
`libmagic` can be used as a static library, but `DllMain` is defined in https://github.com/file/file/blob/87731415de/src/magic.c#L163.
`DllMain` only initialized `_w32_dll_instance`. 
`_w32_dll_instance` is only used in [`get_default_magic`](https://github.com/file/file/blob/87731415de/src/magic.c#L239).
 In fact, when `libmagic` is used as a static library, only https://github.com/file/file/blob/87731415de/src/magic.c#L236 is enough.

2021-11-01 13:26 UTC, julian-r requested changes

2021-11-01 13:26 UTC, julian-r commented on .gitignore
> +; *.cmake
Why committing the `.cmake` files?

2021-11-01 13:26 UTC, julian-r commented on CMakeLists.txt
> +set(FILE_VERSION 5.38)
That would be a downgrade of file to `5.38`, is there a specific reason for this?

2023-03-13 12:43 UTC, closed without merging

2023-03-16 06:40 UTC, Cirn09 commented
Sorry, I noticed your comment on my code only after you closed this PR. I will rewrite the code and open a new PR.

For developers who use this project as a dynamic or static library, the `install` command at the end of the CMakeLists.txt file is necessary. Otherwise, cmake will not generate `.cmake` files for this project as a library. The `cmake/Findpcre2.cmake` file is also necessary, otherwise the result of `cmake install` will not include the content of pcre2.

Also, the suggestion of compiling file as a static library under Windows has been merged into the file source code. Therefore, the implementation solution in this project can be simplified significantly.